# Generated by Django 6.0.2 on 2026-02-08 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("evidence", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="controls.control",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_controls",
                        to="risks.risk",
                    ),
                ),
            ],
            options={
                "unique_together": {("risk", "control")},
            },
        ),
    ]
